//FETCH PUPULAR COCKTAILS

export const FETCH_POPULAR = 'FETCH_POPULAR'
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS'
export const FETCH_POPULAR_ERROR = 'FETCH_POPULAR_ERROR'

// FETCH LATEST COCKTAILS

export const FETCH_LATEST = 'FETCH_LATEST'
export const FETCH_LATEST_SUCCESS = 'FETCH_LALEST_SUCCESS'
export const FETCH_LATEST_ERROR = 'FETCH_LALEST_ERROR'

// FETCH COCKTAIL

export const FETCH_COCKTAIL = 'FETCH_COCKTAIL'
export const FETCH_COCKTAIL_SUCCESS = 'FETCH_COCKTAIL_SUCCESS'
export const FETCH_COCKTAIL_ERROR = 'FETCH_COCKTAIL_ERROR'
