//FETCH PUPULAR COCKTAILS

export const FETCH_POPULAR = 'FETCH_POPULAR'
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS'
export const FETCH_POPULAR_ERROR = 'FETCH_POPULAR_ERROR'

// FETCH LATEST COCKTAILS

export const FETCH_LATEST = 'FETCH_LATEST'
export const FETCH_LATEST_SUCCESS = 'FETCH_LALEST_SUCCESS'
export const FETCH_LATEST_ERROR = 'FETCH_LALEST_ERROR'

// FETCH COCKTAIL

export const FETCH_COCKTAIL = 'FETCH_COCKTAIL'
export const FETCH_COCKTAIL_SUCCESS = 'FETCH_COCKTAIL_SUCCESS'
export const FETCH_COCKTAIL_ERROR = 'FETCH_COCKTAIL_ERROR'

// FETCH RANDOM

export const FETCH_RANDOM = 'FETCH_RANDOM'
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS'
export const FETCH_RANDOM_ERROR = 'FETCH_RANDOM_ERROR'


// UPLOAD IMAGE

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR'

// POST CUSTOM COCKTAIL

export const POST_COCKTAIL = 'POST_COCKTAIL'
export const POST_COCKTAIL_SUCCESS = 'POST_COCKTAIL_SUCCESS'
export const POST_COCKTAIL_ERROR = 'POST_COCKTAIL_ERROR'